---
- include_role:
    name: k3s

- include_role:
    name: dt-activegate-classic
  vars:
    activegate_install_synthetic: true

- name: Install Monaco
  include_role:
    name: monaco-v2

- include_role:
    name: dt-operator

- include_role:
    name: monaco

- include_role:
    name: app-easytravel

- include_role:
    name: app-unguard

- include_role:
    name: app-unguard
    tasks_from: apply-dt-configuration
  vars:
    skip_synthetic_monitor: "false"

- include_role:
    name: app-easytrade

- include_role:
    name: app-easytrade
    tasks_from: apply-dt-configuration

- include_role:
    name: app-hipstershop

- include_role:
    name: app-hipstershop
    tasks_from: apply-dt-configuration
  vars:
    skip_synthetic_monitor: "false"

- include_role:
    name: dashboard




