---
- include_role:
    name: microk8s

- include_role:
    name: dt-activegate-classic
  vars:
    activegate_install_synthetic: true

- name: Install Monaco
  include_role:
    name: monaco-v2

- include_role:
    name: dt-operator

- include_role:
    name: monaco

- include_role:
    name: app-easytravel

- include_role:
    name: app-unguard

- include_role:
    name: app-easytrade

- include_role:
    name: app-hipstershop

# - include_role:
#     name: app-easytrade
#     tasks_from: apply-dt-configuration

# Include and template use case specific values before installing Dashboard
- set_fact:
    include_dashboard_value_file: "{{ role_path }}/templates/demo-apps-dashboard.yml.j2"

- include_role:
    name: dashboard
    tasks_from: template-values-file

- include_role:
    name: dashboard

